# Generated by Django 2.2.10 on 2021-06-07 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_account_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
